"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from '@chakra-ui/react'
//import Navbar from "@/components/navbar/Navbar";
import Navbar2 from "@/components/navbar2/Navbar2"



/*const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({

  children,
}:
 { children: React.ReactNode})
 { return (
    <html lang="en">
      <ChakraProvider>
      <Navbar2 />
        {children}
      </ChakraProvider>
    </html>
  );
}
